version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-4000}:${PORT:-4000}'
    environment:
      - PORT=${PORT:-4000}
      - JWT_SECRET=${JWT_SECRET}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - AI_MODEL=${AI_MODEL}
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/app/.gcloud/kms/google.json
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
      - MONGO_URI=${MONGO_URI}

    volumes:
      - ./.gcloud:/usr/app/.gcloud
      - ./src:/usr/app/src
      - ./package.json:/usr/app/package.json
      - ./bun.lockb:/usr/app/bun.lockb
      - ./tsconfig.json:/usr/app/tsconfig.json
    depends_on:
      - redis
    restart: unless-stopped
    command: ['bun', 'run', 'start:dev']

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped

volumes:
  redis-data:
