import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import {
  UserEntity,
  OrganizationEntity,
  UserTokenEntity,
  SmsVerificationEntity,
  NotificationEntity,
  SessionEntity,
  MessageEntity,
  AgentEntity,
  AgentInstructionEntity,
  ReportEntity,
  TokenUsageEntity,
  SourceEntity,
  CreditTransactionEntity,
  CreditBalanceEntity,
  PlanEntity,
  SubscriptionEntity,
  PaymentEntity,
  FeatureEntity,
  OrganizationFeatureEntity,
} from 'src/entities';
import { InfrastructureModule } from 'src/infrastructure/infrastructure.module';

import {
  AgentInstructionRepository,
  AgentRepository,
  MessageRepository,
  NotificationRepository,
  OrganizationRepository,
  SessionRepository,
  SmsVerificationRepository,
  UserRepository,
  UserTokenRepository,
  ReportRepository,
  TokenUsageRepository,
  SourceRepository,
  CreditTransactionRepository,
  CreditBalanceRepository,
  PlanRepository,
  SubscriptionRepository,
  PaymentRepository,
  UniversalDataRepository,
  FeatureRepository,
  OrganizationFeatureRepository,
} from '.';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      UserEntity,
      OrganizationEntity,
      UserTokenEntity,
      SmsVerificationEntity,
      NotificationEntity,
      SessionEntity,
      MessageEntity,
      AgentEntity,
      AgentInstructionEntity,
      ReportEntity,
      TokenUsageEntity,
      SourceEntity,
      CreditTransactionEntity,
      CreditBalanceEntity,
      PlanEntity,
      SubscriptionEntity,
      PaymentEntity,
      FeatureEntity,
      OrganizationFeatureEntity,
    ]),
    InfrastructureModule,
  ],
  providers: [
    OrganizationRepository,
    UserRepository,
    UserTokenRepository,
    SmsVerificationRepository,
    NotificationRepository,
    SessionRepository,
    MessageRepository,
    AgentRepository,
    AgentInstructionRepository,
    ReportRepository,
    TokenUsageRepository,
    SourceRepository,
    CreditTransactionRepository,
    CreditBalanceRepository,
    PlanRepository,
    SubscriptionRepository,
    PaymentRepository,
    UniversalDataRepository,
    FeatureRepository,
    OrganizationFeatureRepository,
  ],
  exports: [
    OrganizationRepository,
    UserRepository,
    UserTokenRepository,
    SmsVerificationRepository,
    NotificationRepository,
    SessionRepository,
    MessageRepository,
    AgentRepository,
    AgentInstructionRepository,
    ReportRepository,
    TokenUsageRepository,
    SourceRepository,
    CreditTransactionRepository,
    CreditBalanceRepository,
    PlanRepository,
    SubscriptionRepository,
    PaymentRepository,
    UniversalDataRepository,
    FeatureRepository,
    OrganizationFeatureRepository,
  ],
})
export class RepositoriesModule {}
