/**
 * Compile the Toro Result Sales business-knowledge source set under `data/docs/`
 * into a single Markdown file at `data/docs/compiled/toro-business-knowledge.md`.
 *
 * Usage:
 *   bun run analytics:compile-toro-docs
 *
 * Idempotent: overwrites the output. Files are concatenated in deterministic
 * (sorted-by-relative-path) order, separated by `---`, with a level-1 header
 * containing the source path prepended to each section.
 *
 * Source set (intentionally narrow — business knowledge only):
 *   - data/docs/modules/**\/*.md   (recursive; includes the `campaigns/` subfolder)
 *   - data/docs/vsale-raffles-api.md
 *   - data/docs/discount-lottery-api.md
 *
 * Excluded by design:
 *   - data/docs/auth/**, data/docs/architecture/**, data/docs/reference/**,
 *     data/docs/integrations/**, data/docs/index.md, data/docs/contributing.md
 *   - data/docs/compiled/**  (do not re-ingest the compiled output)
 */
import { Dirent, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const ROOT = resolve(__dirname, '..');
const DOCS = resolve(ROOT, 'data/docs');
const OUT_DIR = resolve(DOCS, 'compiled');
const OUT_FILE = resolve(OUT_DIR, 'toro-business-knowledge.md');

/**
 * Recursively walk `dir` and return every `.md` file path relative to `base`.
 * Skips directories that cannot be read (e.g., missing under a fresh checkout).
 */
function walkMarkdownFiles(dir: string, base: string): string[] {
  let entries: Dirent[];
  try {
    entries = readdirSync(dir, { withFileTypes: true, encoding: 'utf-8' });
  } catch {
    return [];
  }

  const out: string[] = [];
  for (const entry of entries) {
    const abs = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walkMarkdownFiles(abs, base));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith('.md')) {
      const rel = abs.slice(base.length + 1).replace(/\\/g, '/');
      out.push(rel);
    }
  }
  return out;
}

/**
 * Read a single explicit source file relative to `data/docs/`. Returns `null`
 * when the file does not exist so the caller can skip it silently.
 */
function readOptionalRelative(rel: string): string | null {
  const abs = resolve(DOCS, rel);
  try {
    statSync(abs);
  } catch {
    return null;
  }
  return rel;
}

function collectSourceFiles(): string[] {
  const moduleFiles = walkMarkdownFiles(resolve(DOCS, 'modules'), DOCS);
  const rootFiles = [
    readOptionalRelative('vsale-raffles-api.md'),
    readOptionalRelative('discount-lottery-api.md'),
  ].filter((p): p is string => p !== null);

  const all = [...moduleFiles, ...rootFiles];
  // Deduplicate, then sort deterministically by relative path.
  return Array.from(new Set(all)).sort();
}

async function main(): Promise<void> {
  const files = collectSourceFiles();
  if (files.length === 0) {
    throw new Error(
      `No source markdown files found under ${DOCS}. ` +
        'Ensure the data/docs/ tree is populated before compiling.',
    );
  }

  const sections = files.map((rel) => {
    const abs = resolve(DOCS, rel);
    const body = readFileSync(abs, 'utf-8').trim();
    return `# data/docs/${rel}\n\n${body}`;
  });

  const header = [
    '<!-- Auto-generated by scripts/compile-toro-docs.ts. Do not edit by hand. -->',
    '<!-- Run `bun run analytics:compile-toro-docs` to regenerate. -->',
    '',
    '# Toro Result Sales — Business Knowledge',
    '',
    `> Compiled ${new Date().toISOString().slice(0, 10)} from ${files.length} source files.`,
    '',
  ].join('\n');

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_FILE, `${header}\n${sections.join('\n\n---\n\n')}\n`, 'utf-8');
  console.log(`Wrote ${OUT_FILE} (${sections.length} sections)`);
}

void main().catch((err) => {
  console.error(err);
  process.exit(1);
});
